/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Catalog
         * @description Lista marts Gold disponiveis com metadata, contagens e tags.
         */
        get: operations["get_catalog_api_data_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Timeseries
         * @description Serie temporal de um indicador para um pais (multi-fonte).
         */
        post: operations["get_timeseries_api_data_timeseries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Compare
         * @description Comparacao de varios paises em um indicador-ano-fonte.
         */
        post: operations["post_compare_api_data_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Ranking
         * @description Ranking de paises em um indicador, opcionalmente filtrado por grouping.
         */
        post: operations["post_ranking_api_data_ranking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CompareRequest
         * @description Comparacao de varios paises em um indicador para um ano.
         */
        CompareRequest: {
            /**
             * Indicator
             * @enum {string}
             */
            indicator: "GASTO_EDU_PIB" | "LITERACY_15M";
            /**
             * Countries
             * @description Lista de codigos ISO-3 a comparar (1 a 50 paises).
             */
            countries: string[];
            /** Year */
            year: number;
            /**
             * Source
             * @description Fonte canonica para a comparacao (default: worldbank).
             * @default worldbank
             * @enum {string}
             */
            source: "worldbank" | "unesco" | "oecd" | "eurostat" | "ipea" | "cepalstat";
        };
        /**
         * DataResponse
         * @description Envelope padrao: {data: [...], meta: {...}}.
         */
        DataResponse: {
            /** Data */
            data: {
                [key: string]: unknown;
            }[];
            meta: components["schemas"]["ResponseMeta"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * RankingRequest
         * @description Ranking de paises em um indicador, opcionalmente filtrado por grupo.
         */
        RankingRequest: {
            /**
             * Indicator
             * @enum {string}
             */
            indicator: "GASTO_EDU_PIB" | "LITERACY_15M";
            /**
             * Year
             * @description Ano especifico. None = ano mais recente disponivel.
             */
            year?: number | null;
            /**
             * Grouping
             * @description Filtra por grupo analitico (oecd, latam, ...). None = global.
             */
            grouping?: ("oecd" | "oecd_g7" | "latam_oecd" | "latam" | "brics" | "asia" | "africa_mena" | "europe_other") | null;
            /**
             * Source
             * @default worldbank
             * @enum {string}
             */
            source: "worldbank" | "unesco" | "oecd" | "eurostat" | "ipea" | "cepalstat";
            /**
             * Limit
             * @default 20
             */
            limit: number;
        };
        /**
         * ResponseMeta
         * @description Metadados que acompanham toda resposta de dados.
         *
         *     Permite que o frontend e os agentes saibam qual foi a abrangencia
         *     da query sem precisar contar linhas.
         */
        ResponseMeta: {
            /** Total Rows */
            total_rows: number;
            /** Query Ms */
            query_ms?: number | null;
            /** Sources */
            sources?: string[] | null;
            /** Notes */
            notes?: string[] | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * TimeseriesRequest
         * @description Request para serie temporal de um indicador-pais.
         */
        TimeseriesRequest: {
            /**
             * Indicator
             * @enum {string}
             */
            indicator: "GASTO_EDU_PIB" | "LITERACY_15M";
            /**
             * Country Iso3
             * @description Codigo ISO-3166 alpha-3 (3 letras maiusculas).
             */
            country_iso3: string;
            /**
             * Year Start
             * @default 2000
             */
            year_start: number;
            /**
             * Year End
             * @default 2024
             */
            year_end: number;
            /**
             * Sources
             * @description Filtra por fontes (default: todas as disponiveis para o indicador).
             */
            sources?: ("worldbank" | "unesco" | "oecd" | "eurostat" | "ipea" | "cepalstat")[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_catalog_api_data_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse"];
                };
            };
        };
    };
    get_timeseries_api_data_timeseries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeseriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_compare_api_data_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_ranking_api_data_ranking_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RankingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
